[build-system]
requires = ["setuptools>=30.3.0", "wheel", "setuptools_scm", "pyscaffold>=3.2a0,<3.3a0"]

[tool.black]
line-length = 100
py36 = false
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
