#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""simple movement test"""

import numpy as np
from hera_display_games.core import board
import time

my_sprite = board.Sprite(np.array([0, 0]))

my_board = board.Board(sprites=[my_sprite])
my_board.draw()

directions = ["r", "r", "dl", "ur", "ur", "ul"]

for dir in directions:
    time.sleep(1)
    my_sprite.move(dir)
    my_board.draw()
